/*******************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.1.
 *
 * You need to add your implementation here to:
 *    - get telemetry data from device/sensor
 *    - set read-only property data
 *    - handle read-write property callback
 *    - process device command
 *
 * Generated Date: 2019年9月2日
 *******************************************************************************************/

#include "ReButton_impl.h"
#include "utilities/digitaltwin_serializer.h"
#include "utilities/deviceinfo_interface.h"
#include "utilities/battery_interface.h"
#include "utilities/pushbutton_interface.h"
#include "utilities/temphumidsensor_interface.h"
#include "../helper/RebuttonHelper.h"

#define Payload_Buffer_Size 256

volatile int ReButton_Property_Pending_Flag = 0;
volatile int ReButton_Telemetry_Pending_Flag = 0;

double Battery_Telemetry_ReadBatteryVoltage()
{
    double voltage = ReadBatteryVoltage();
    LogInfo("Battery Voltage %02f", voltage);
	return 3.0;
}

double TempHumidSensor_Telemetry_ReadTemperature()
{
	float temperature = GetTemperature();
	LogInfo("Temperature %02f", temperature);
	return temperature;
}

double TempHumidSensor_Telemetry_ReadHumidity()
{
	float humidity = GetHumidity();
	LogInfo("Humidity %02f", humidity);
	return humidity;
}

PUSHBUTTON_ACTIONNUM PushButton_Telemetry_ReadActionNum()
{
	LogInfo("PushButton_Telemetry_ReadActionNum =====================\r\n");
	// switch (Action)
	// {
	// case ACTION_1:
	// 	return PUSHBUTTON_ACTIONNUM_SingleClick;
	// case ACTION_2:
	// 	return PUSHBUTTON_ACTIONNUM_DoubleClick;
	// case ACTION_3:
	// 	return PUSHBUTTON_ACTIONNUM_TripleClick;
	// case ACTION_10:
	// 	return PUSHBUTTON_ACTIONNUM_LongPress;
	// case ACTION_11:
	// 	return PUSHBUTTON_ACTIONNUM_SuperLongPress;
	// default:
	// 	return PUSHBUTTON_ACTIONNUM_ERROR;
	// }
    return PUSHBUTTON_ACTIONNUM_SingleClick;
}

char* PushButton_Telemetry_ReadMessage()
{
	LogInfo("PushButton_Telemetry_ReadMessage =====================\r\n");
	// switch (Action)
	// {
	// case ACTION_1:
	// 	return Config.Message1;
	// case ACTION_2:
	// 	return Config.Message2;
	// case ACTION_3:
	// 	return Config.Message3;
	// case ACTION_10:
	// 	return Config.Message10;
	// case ACTION_11:
	// 	return Config.Message11;
	// default:
	// 	return "UNKNOWN";
	// }
    return "UNKNOWN";
}

void SendTelemetry_Succeeded_Callback(const char* interfaceName, const char* telemetryName)
{
    // If needed, put your business logic here to handle the confirmation of the delivery for device telemetry on success.

    LogInfo("DigitalTwin successfully delivered telemetry message for %s::%s", interfaceName, telemetryName);
}

void SendTelemetry_Error_Callback(const char* interfaceName, const char* telemetryName)
{
    // If needed, put your business logic here to handle the confirmation of the delivery for device telemetry on failure.

    LogInfo("DigitalTwin failed to deliver telemetry message for %s::%s", interfaceName, telemetryName);
}

void ReportProperty_Succeeded_Callback(const char* interfaceName, const char* propertyName)
{
    // If needed, put your business logic here to handle the result callback reporting property on success.
    LogInfo("DigitalTwin successfully report writable property for %s::%s", interfaceName, propertyName);
}

void ReportProperty_Error_Callback(const char* interfaceName, const char* propertyName)
{
    // If needed, put your business logic here to handle the result callback of reporting property on failure.
    LogInfo("DigitalTwin failed to report writable property for %s::%s", interfaceName, propertyName);
}

char* DeviceInfo_Property_GetManufacturer()
{
    return "Seeed";
}

char* DeviceInfo_Property_GetModel()
{
    return "ReButton";
}

char* DeviceInfo_Property_GetSwVersion()
{
    return GetSwVersion();
}

char* DeviceInfo_Property_GetOsName()
{
    return "Arduino+Mbed";
}

char* DeviceInfo_Property_GetProcessorArchitecture()
{
    return "EMW3166";
}

char* DeviceInfo_Property_GetProcessorManufacturer()
{
    return "MxChip";
}

long DeviceInfo_Property_GetTotalStorage()
{
    return 1024 * 1024;
}

long DeviceInfo_Property_GetTotalMemory()
{
    return 256 * 1024;
}



